# This file was generated by the docusign_rest:generate_config rake task.
# You can run 'rake docusign_rest:generate_config' as many times as you need
# to replace the content of this file with a new config.

require 'docusign_rest'

DocusignRest.configure do |config|
  config.username       = 'chintan@pennywhale.com'
  config.password       = 'gp317a45'
  config.integrator_key = '03cd00cf-e8bb-4bef-a10e-bcef5a56a733'
  config.account_id     = '1729286'
  #config.endpoint       = 'https://www.docusign.net/restapi'
  #config.api_version    = 'v1'
end

