# Action Cable uses Redis by default to administer connections, channels, and sending/receiving messages over the WebSocket.
production:
  adapter: redis
  url: redis://redistogo:b4b45861c1a7ace9afe4ace3da8c94ac@viperfish.redistogo.com:10432/

development:
  adapter: async

test:
  adapter: async
