default: &default
  adapter: postgresql
  encoding: utf8
  pool: 5

development:
  <<: *default

test:
  <<: *default

production:
  <<: *default
  host: <%= ENV['DATABASE_HOST'] %>
  database: <%= ENV['DATABASE_NAME'] %>
  username: <%= ENV['DATABASE_USERNAME'] %>
