default: &default
  adapter: postgresql
  encoding: utf8
  pool: 5
  username: postgres
  password: root
  host: localhost

development:
  <<: *default
  database: deals

test:
  <<: *default
  database: deals_test

production:
  <<: *default
  database: <%= ENV['DATABASE_NAME'] %>
  username: <%= ENV['DATABASE_USERNAME'] %>
  password: <%= ENV['DATABASE_PASSWORD'] %>